services:
  auth:
    image: auth
    build:
      context: ./
    container_name: auth
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_PORT=5432
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    command: ["app"]

  postgres:
    image: postgres:12.9
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth    
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data

volumes:
  pg_data:
  redis:
