version: "3.9"

services:
  auth:
    image: auth
    build:
      context: .
    container_name: auth
    ports:
      - "3000:8080"
    env_file:
      - .docker.env
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12.9
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth    
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
      # TODO create a redis.conf file
      # - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  pg_data:
  redis:
