FROM golang:1.20.2

# Create and change to the app directory.
WORKDIR /app

# Required by github.com/githubnemo/CompileDaemon
ENV PROJECT_DIR=/app \
    GO111MODULE=on \
    CGO_ENABLED=0

# Retrieve application dependencies.
COPY go.* ./
RUN go mod download && go mod verify

# Copy local code to the container image.
COPY . ./

# Create build directory
RUN mkdir "/build"

# Install CompileDaemon
RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon

EXPOSE 8080

# CompileDaemon will watch for changes in the project directory and automatically rebuild the code.
ENTRYPOINT CompileDaemon -build="go build -o /build/app cmd/main.go" -command="/build/app"
